name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
      - name: approve label
        uses: abinoda/label-when-approved-action@1.0.5
        env:
          APPROVALS: 1
          GITHUB_TOKEN: GITHUB_TOKEN
          ADD_LABEL: can merge
